'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.18444
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Form_Demarrage
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("IDEALTAKE.Form_Demarrage", GetType(Form_Demarrage).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=895,Y=133}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorker_Diagnostic_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorker_Diagnostic.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=952,Y=172}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorker_RA_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorker_RA.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=717,Y=133}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorker_RG_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorker_RG.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=541,Y=133}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorker_RS_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorker_RS.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=893,Y=328}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerAjoutCompteGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerAjoutCompteGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=258,Y=211}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerAjoutEnregistrement_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerAjoutEnregistrement.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=367}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerAjoutLiensRéférences_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerAjoutLiensRéférences.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=615,Y=328}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerAjoutTreeviewPosition_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerAjoutTreeviewPosition.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=289}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerAuthentificationtCompteGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerAuthentificationtCompteGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=222,Y=445}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerChargementEnregistrement_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerChargementEnregistrement.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=172}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerDetailsEnregistrementW1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerDetailsEnregistrementW1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=246,Y=133}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerDetailsEnregistrementW2_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerDetailsEnregistrementW2.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=768,Y=211}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerDetailsEnregistrementW3_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerDetailsEnregistrementW3.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=599,Y=406}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerMiniVLCPlayer_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerMiniVLCPlayer.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=744,Y=445}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerMiseàJourEnregistrement_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerMiseàJourEnregistrement.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=341,Y=250}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerRechercheGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerRechercheGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=736,Y=367}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerRécupérationCompteGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerRécupérationCompteGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=375,Y=289}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerSupprimeEnregistrement_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerSupprimeEnregistrement.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=303,Y=406}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerSupprimeLiensRéférences_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerSupprimeLiensRéférences.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=250}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerSupprimerCompteGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerSupprimerCompteGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=445}.
        '''</summary>
        Friend Shared ReadOnly Property BackgroundWorkerTransfert_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundWorkerTransfert.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=968,Y=16}.
        '''</summary>
        Friend Shared ReadOnly Property ColorDialog1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ColorDialog1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=653,Y=94}.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuStrip1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenuStrip1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=810,Y=94}.
        '''</summary>
        Friend Shared ReadOnly Property ContextMenuStrip2_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ContextMenuStrip2.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=242,Y=328}.
        '''</summary>
        Friend Shared ReadOnly Property ErrorProvider1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ErrorProvider1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Windows.Forms.ImageListStreamer.
        '''</summary>
        Friend Shared ReadOnly Property ImageList_TabControl1_ImageStream() As System.Windows.Forms.ImageListStreamer
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageList_TabControl1.ImageStream", resourceCulture)
                Return CType(obj,System.Windows.Forms.ImageListStreamer)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=164,Y=16}.
        '''</summary>
        Friend Shared ReadOnly Property ImageList_TabControl1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageList_TabControl1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=538,Y=94}.
        '''</summary>
        Friend Shared ReadOnly Property MenuStrip1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuStrip1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Boolean semblable à True.
        '''</summary>
        Friend Shared ReadOnly Property MenuStrip2_Locked() As Boolean
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuStrip2.Locked", resourceCulture)
                Return CType(obj,Boolean)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=967,Y=94}.
        '''</summary>
        Friend Shared ReadOnly Property MenuStrip2_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("MenuStrip2.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=55}.
        '''</summary>
        Friend Shared ReadOnly Property OpenFileDialog1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenFileDialog1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=340,Y=16}.
        '''</summary>
        Friend Shared ReadOnly Property PageSetupDialog1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("PageSetupDialog1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property PictureBox10_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox10.BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property PictureBox9_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PictureBox9.BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=258,Y=55}.
        '''</summary>
        Friend Shared ReadOnly Property PrintDialog1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintDialog1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=24,Y=16}.
        '''</summary>
        Friend Shared ReadOnly Property PrintDocument1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("PrintDocument1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=729,Y=16}.
        '''</summary>
        Friend Shared ReadOnly Property Restauration_Base_OpenFileDialog_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Restauration_Base_OpenFileDialog.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=133}.
        '''</summary>
        Friend Shared ReadOnly Property RS_Reference_ContextMenuStrip_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("RS_Reference_ContextMenuStrip.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=401,Y=94}.
        '''</summary>
        Friend Shared ReadOnly Property SaveFileDialog1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("SaveFileDialog1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property TabPage1_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TabPage1.BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property TabPage3_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TabPage3.BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property TabPage4_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TabPage4.BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property TabPage5_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TabPage5.BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property TabPage6_BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TabPage6.BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=790,Y=55}.
        '''</summary>
        Friend Shared ReadOnly Property Tâche_de_fond_RS_MOTS_CLEFS_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Tâche_de_fond_RS_MOTS_CLEFS.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=627,Y=55}.
        '''</summary>
        Friend Shared ReadOnly Property Tâche_de_fond_SAPI_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Tâche_de_fond_SAPI.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=377,Y=55}.
        '''</summary>
        Friend Shared ReadOnly Property Tâche_de_fond_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Tâche_de_fond.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à 
        '''    --------------------------------------------------------------
        '''
        '''   Ce logiciel a été conçu afin de simplifier vos recherches sur des
        '''   documents  personnel ou professionnel : 
        '''
        '''    - Schémas électriques
        '''    - Schémas synoptiques
        '''    - Notices + photos
        '''    - Fiches Produits
        '''
        '''
        '''   Vous disposez, à cet effet, de sept onglets :
        '''
        '''
        '''   1/ Gestion de Base
        '''    
        '''    Utilisé pour la gestion de la base de données du moteur de recherche,
        '''    géré uniquement par un gestionnaire ou un administrateur [le reste de la chaîne a été tronqué]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Texte_Aide_Text() As String
            Get
                Return ResourceManager.GetString("Texte_Aide.Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=492,Y=16}.
        '''</summary>
        Friend Shared ReadOnly Property Timer_Verification_excution_SAPI5_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Timer_Verification_excution_SAPI5.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=1018,Y=55}.
        '''</summary>
        Friend Shared ReadOnly Property Timer1EtatServeur_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Timer1EtatServeur.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=94}.
        '''</summary>
        Friend Shared ReadOnly Property Timer2EtatServeur_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Timer2EtatServeur.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=168,Y=94}.
        '''</summary>
        Friend Shared ReadOnly Property Timer3AutocompleteRsMotsClefs_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("Timer3AutocompleteRsMotsClefs.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=484}.
        '''</summary>
        Friend Shared ReadOnly Property TimerChargementEnregistrement_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerChargementEnregistrement.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=372,Y=328}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatAjoutCompteGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatAjoutCompteGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=529,Y=445}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatAjoutEnregistrement_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatAjoutEnregistrement.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=516,Y=367}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatAjoutLiensRéférences_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatAjoutLiensRéférences.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=328}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatAjoutTreeviewPosition_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatAjoutTreeviewPosition.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=885,Y=289}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatAuthentificationtCompteGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatAuthentificationtCompteGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=473,Y=172}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatDetailsEnregistrementW1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatDetailsEnregistrementW1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=211}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatDetailsEnregistrementW2_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatDetailsEnregistrementW2.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=527,Y=211}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatDetailsEnregistrementW3_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatDetailsEnregistrementW3.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=312,Y=172}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatDiagnostic_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatDiagnostic.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=833,Y=172}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatRA_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatRA.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=290,Y=367}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatRechercheGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatRechercheGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=17,Y=406}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatRécupérationCompteGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatRécupérationCompteGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=714,Y=172}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatRG_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatRG.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=510,Y=55}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatRS_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatRS.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=834,Y=406}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatSupprimeLiensRéférences_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatSupprimeLiensRéférences.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=621,Y=250}.
        '''</summary>
        Friend Shared ReadOnly Property TimerEtatSupprimerCompteGestionBase_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerEtatSupprimerCompteGestionBase.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=249,Y=484}.
        '''</summary>
        Friend Shared ReadOnly Property TimerMiseàJourEnregistrement_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerMiseàJourEnregistrement.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=667,Y=289}.
        '''</summary>
        Friend Shared ReadOnly Property TimerSupprimeEnregistrement_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerSupprimeEnregistrement.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une ressource localisée de type System.Drawing.Point semblable à {X=159,Y=55}.
        '''</summary>
        Friend Shared ReadOnly Property ToolTip1_TrayLocation() As System.Drawing.Point
            Get
                Dim obj As Object = ResourceManager.GetObject("ToolTip1.TrayLocation", resourceCulture)
                Return CType(obj,System.Drawing.Point)
            End Get
        End Property
    End Class
End Namespace
